// <auto-generated />
using System;
using Backend_SIGMA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_SIGMA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_SIGMA.Models.EstatusSiniestro", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatus"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstatus");

                    b.ToTable("EstatusSiniestros");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Mantenimiento", b =>
                {
                    b.Property<int>("IdMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMantenimiento"));

                    b.Property<decimal?>("Costo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<int?>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegistradoPor")
                        .HasColumnType("int");

                    b.HasKey("IdMantenimiento");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdTipo");

                    b.HasIndex("IdVehiculo");

                    b.HasIndex("RegistradoPor");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Correo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Siniestro", b =>
                {
                    b.Property<int>("IdSiniestro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSiniestro"));

                    b.Property<int?>("AtendidoPor")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdConductor")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSiniestro");

                    b.HasIndex("AtendidoPor");

                    b.HasIndex("IdConductor");

                    b.HasIndex("IdEstatus");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Siniestros");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.SiniestroEvidencia", b =>
                {
                    b.Property<int>("IdEvidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvidencia"));

                    b.Property<string>("ArchivoBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdSiniestro")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("FOTO");

                    b.HasKey("IdEvidencia");

                    b.HasIndex("IdSiniestro");

                    b.ToTable("SiniestroEvidencias");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.TipoMantenimiento", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposMantenimiento");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int?>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KilometrajeActual")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroEconomico")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placas")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("NumeroEconomico")
                        .IsUnique()
                        .HasFilter("[NumeroEconomico] IS NOT NULL");

                    b.HasIndex("Placas")
                        .IsUnique()
                        .HasFilter("[Placas] IS NOT NULL");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasFilter("[Vin] IS NOT NULL");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.VehiculoAsignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("VehiculoAsignaciones");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Mantenimiento", b =>
                {
                    b.HasOne("Backend_SIGMA.Models.Proveedor", "Proveedor")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend_SIGMA.Models.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_SIGMA.Models.Vehiculo", "Vehiculo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_SIGMA.Models.Usuario", "UsuarioRegistro")
                        .WithMany("MantenimientosRegistrados")
                        .HasForeignKey("RegistradoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Proveedor");

                    b.Navigation("TipoMantenimiento");

                    b.Navigation("UsuarioRegistro");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Siniestro", b =>
                {
                    b.HasOne("Backend_SIGMA.Models.Usuario", "Atendido")
                        .WithMany("SiniestrosAtendidos")
                        .HasForeignKey("AtendidoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend_SIGMA.Models.Usuario", "Conductor")
                        .WithMany("SiniestrosComoConductor")
                        .HasForeignKey("IdConductor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_SIGMA.Models.EstatusSiniestro", "Estatus")
                        .WithMany("Siniestros")
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_SIGMA.Models.Vehiculo", "Vehiculo")
                        .WithMany("Siniestros")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendido");

                    b.Navigation("Conductor");

                    b.Navigation("Estatus");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.SiniestroEvidencia", b =>
                {
                    b.HasOne("Backend_SIGMA.Models.Siniestro", "Siniestro")
                        .WithMany("Evidencias")
                        .HasForeignKey("IdSiniestro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siniestro");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Usuario", b =>
                {
                    b.HasOne("Backend_SIGMA.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.VehiculoAsignacion", b =>
                {
                    b.HasOne("Backend_SIGMA.Models.Usuario", "Usuario")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_SIGMA.Models.Vehiculo", "Vehiculo")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.EstatusSiniestro", b =>
                {
                    b.Navigation("Siniestros");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Proveedor", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Siniestro", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.TipoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Usuario", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("MantenimientosRegistrados");

                    b.Navigation("SiniestrosAtendidos");

                    b.Navigation("SiniestrosComoConductor");
                });

            modelBuilder.Entity("Backend_SIGMA.Models.Vehiculo", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Mantenimientos");

                    b.Navigation("Siniestros");
                });
#pragma warning restore 612, 618
        }
    }
}
