export const VEHICULOS_LOADING = "VEHICULOS_LOADING";
export const VEHICULOS_ERROR = "VEHICULOS_ERROR";
export const CLEAR_VEHICULOS_ERROR = "CLEAR_VEHICULOS_ERROR";

export const GET_VEHICULOS_SUCCESS = "GET_VEHICULOS_SUCCESS";
export const GET_VEHICULO_SUCCESS = "GET_VEHICULO_SUCCESS";
export const SET_SELECTED_VEHICULO = "SET_SELECTED_VEHICULO";
export const CREATE_VEHICULO_SUCCESS = "CREATE_VEHICULO_SUCCESS";
export const UPDATE_VEHICULO_SUCCESS = "UPDATE_VEHICULO_SUCCESS";
export const DELETE_VEHICULO_SUCCESS = "DELETE_VEHICULO_SUCCESS";