// Loading / Error
export const SINIESTROS_LOADING = "SINIESTROS_LOADING";
export const SINIESTROS_ERROR = "SINIESTROS_ERROR";
export const CLEAR_SINIESTROS_ERROR = "CLEAR_SINIESTROS_ERROR";

// Siniestros
export const GET_SINIESTROS_SUCCESS = "GET_SINIESTROS_SUCCESS";
export const GET_SINIESTRO_SUCCESS = "GET_SINIESTRO_SUCCESS";
export const CREATE_SINIESTRO_SUCCESS = "CREATE_SINIESTRO_SUCCESS";
export const UPDATE_SINIESTRO_SUCCESS = "UPDATE_SINIESTRO_SUCCESS";
export const DELETE_SINIESTRO_SUCCESS = "DELETE_SINIESTRO_SUCCESS";
export const CAMBIAR_ESTATUS_SINIESTRO_SUCCESS = "CAMBIAR_ESTATUS_SINIESTRO_SUCCESS";

// Evidencias
export const GET_EVIDENCIAS_SUCCESS = "GET_EVIDENCIAS_SUCCESS";
export const ADD_EVIDENCIA_SUCCESS = "ADD_EVIDENCIA_SUCCESS";
export const DELETE_EVIDENCIA_SUCCESS = "DELETE_EVIDENCIA_SUCCESS";

// Estatus
export const GET_ESTATUS_SUCCESS = "GET_ESTATUS_SUCCESS";

// Estadísticas
export const GET_ESTADISTICAS_SUCCESS = "GET_ESTADISTICAS_SUCCESS";

// Selected
export const SET_SELECTED_SINIESTRO = "SET_SELECTED_SINIESTRO";
export const SET_SELECTED_ESTATUS = "SET_SELECTED_ESTATUS";