export const MANTENIMIENTOS_LOADING = "MANTENIMIENTOS_LOADING";
export const MANTENIMIENTOS_ERROR = "MANTENIMIENTOS_ERROR";
export const CLEAR_MANTENIMIENTOS_ERROR = "CLEAR_MANTENIMIENTOS_ERROR";

// Mantenimientos
export const GET_MANTENIMIENTOS_SUCCESS = "GET_MANTENIMIENTOS_SUCCESS";
export const GET_MANTENIMIENTO_SUCCESS = "GET_MANTENIMIENTO_SUCCESS";
export const CREATE_MANTENIMIENTO_SUCCESS = "CREATE_MANTENIMIENTO_SUCCESS";
export const UPDATE_MANTENIMIENTO_SUCCESS = "UPDATE_MANTENIMIENTO_SUCCESS";
export const DELETE_MANTENIMIENTO_SUCCESS = "DELETE_MANTENIMIENTO_SUCCESS";

// Tipos de mantenimiento
export const GET_TIPOS_SUCCESS = "GET_TIPOS_SUCCESS";
export const CREATE_TIPO_SUCCESS = "CREATE_TIPO_SUCCESS";
export const UPDATE_TIPO_SUCCESS = "UPDATE_TIPO_SUCCESS";
export const DELETE_TIPO_SUCCESS = "DELETE_TIPO_SUCCESS";

// Proveedores
export const GET_PROVEEDORES_SUCCESS = "GET_PROVEEDORES_SUCCESS";
export const CREATE_PROVEEDOR_SUCCESS = "CREATE_PROVEEDOR_SUCCESS";
export const UPDATE_PROVEEDOR_SUCCESS = "UPDATE_PROVEEDOR_SUCCESS";
export const DELETE_PROVEEDOR_SUCCESS = "DELETE_PROVEEDOR_SUCCESS";

export const SET_SELECTED_MANTENIMIENTO = "SET_SELECTED_MANTENIMIENTO";
export const SET_SELECTED_TIPO = "SET_SELECTED_TIPO";
export const SET_SELECTED_PROVEEDOR = "SET_SELECTED_PROVEEDOR";